//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.ArHat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int sid { get; set; }
        public string sname { get; set; }
        public Nullable<int> sage { get; set; }
        public int cid { get; set; }
    
        public virtual @class @class { get; set; }
    }
}
